repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff check
        language: system
        entry: uv run ruff check
        types: [python]

      - id: ruff-format
        name: Ruff format
        language: system
        entry: uv run ruff format
        types: [python]

      - id: pyright
        name: Pyright
        language: system
        entry: uv run basedpyright
        types: [python]
